# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-x-ray

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  tracing: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required) 
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
plugins:
  - serverless-plugin-tracing

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    healthcheck:
      tracing: true
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
  helloError:
    handler: error.thisHasError
    healthcheck:
      tracing: true
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-error
          method: get
          cors: true
